### ISSUE TITLE
Prefix match not working as expected

### ISSUE THREAD

**Issue by yungwood** [yungwood/ical-filter-proxy#13]
I noticed prefix match is not working as expected.

Config:
```yaml
- description: "Remove Hidden events"
  remove: true
  match:
    summary:
      prefix: '[Hidden]'
```

This is not matching events such as `[Hidden] Title here`.
